name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} --password-stdin ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t benhooper.org .
      - name: Tags
        run: |
          docker tag back ${{ secrets.DOCKER_USER }}/benhooper.org:${{ github.sha }}
          docker tag back ${{ secrets.DOCKER_USER }}/benhooper.org:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/benhooper.org:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/benhooper.org:latest
